import { cn } from "@/lib/utils";
import { Inter } from "next/font/google";
import { FilesProvider } from "./context/filesContext";
import { readProviderCookies } from "./context/server";
import "./globals.css";

const fontSans = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const providerValues = await readProviderCookies();

  return (
    <FilesProvider {...providerValues}>
      <html lang="en" className="h-full dark">
        <body className={cn(fontSans.variable, "h-full font-sans")}>
          {children}
        </body>
      </html>
    </FilesProvider>
  );
}
